Test (#189)
- Run tests on CI
- Remove `idl-build` due to compile error

```
Error: Function _ZN14regex_automata4meta8strategy3new17hff17942e8ccc6a03E Stack offset of 5208 exceeded max offset of 4096 by 1112 bytes, please minimize large stack variables. Estimated function frame size: 12416 bytes. Exceeding the maximum stack offset may cause undefined behavior during execution.
```

Build + Test
```bash
cargo-build-sbf --manifest-path programs/validator-history/Cargo.toml && \
    cargo-build-sbf --manifest-path programs/steward/Cargo.toml && \
    SBF_OUT_DIR=$(pwd)/target/sbpf-solana-solana/release \
    RUST_MIN_STACK=10000000 \
    cargo nextest run --all-features --package tests
```