Test: Get new latest block hash (#286)
### Problem

- Sometimes this test fails


https://github.com/jito-foundation/stakenet/actions/runs/23811001034/job/69400072645

```bash
    thread 'steward::test_internal_lamport_tracking::test_internal_lamport_tracking_with_deposit' panicked at /home/runner/work/stakenet/stakenet/tests/src/steward_fixtures.rs:868:9:
    assertion failed: result.result.is_ok()
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

  Cancelling due to test failure: 15 tests still running
        PASS [   0.730s] (196/264) tests::mod steward::test_state_methods::test_directed_stake_whitelist_capacity_limits
        PASS [   1.274s] (197/264) tests::mod steward::test_spl_passthrough::test_increase_validator_stake
        PASS [   1.283s] (198/264) tests::mod steward::test_spl_passthrough::test_remove_validator_from_pool
        PASS [   3.785s] (199/264) tests::mod steward::test_internal_lamport_tracking::test_internal_lamport_tracking_with_deposit_meeting_target
        PASS [   1.977s] (200/264) tests::mod steward::test_spl_passthrough::test_add_validator_to_pool
        PASS [   1.372s] (201/264) tests::mod steward::test_spl_passthrough::test_set_preferred_validator
        PASS [   1.301s] (202/264) tests::mod steward::test_spl_passthrough::test_set_staker
        PASS [   1.110s] (203/264) tests::mod steward::test_steward::test_auto_add_validator_to_pool
        PASS [   0.991s] (204/264) tests::mod steward::test_steward::test_blacklist
        PASS [   0.974s] (205/264) tests::mod steward::test_steward::test_blacklist_edge_cases
        PASS [   4.431s] (206/264) tests::mod steward::test_internal_lamport_tracking::test_internal_lamport_tracking_with_withdraw
        PASS [   1.665s] (207/264) tests::mod steward::test_steward::test_auto_remove
        PASS [   1.592s] (208/264) tests::mod steward::test_steward::test_instant_remove_validator
        PASS [   5.615s] (209/264) tests::mod steward::test_internal_lamport_tracking::test_internal_lamport_tracking_with_withdraw_remainder
        PASS [   4.182s] (210/264) tests::mod steward::test_steward::test_auto_remove_validator_states
────────────
     Summary [  14.208s] 210/264 tests run: 209 passed, 1 failed, 0 skipped
        FAIL [   3.655s] (195/264) tests::mod steward::test_internal_lamport_tracking::test_internal_lamport_tracking_with_deposit
warning: 54/264 tests were not run due to test failure (run with --no-fail-fast to run all tests, or run with --max-fail)

```

### Solution

- The test used old blockhash and got expired error, so get latest
blockhash