Keeper: Fix vote state (#285)
### Problem

```bash
[2026-03-31T05:10:12Z INFO  stakenet_keeper] Pre-fetching data for update...(301)
[2026-03-31T05:10:13Z INFO  stakenet_keeper] Creating missing accounts...(301)
[2026-03-31T05:10:13Z INFO  stakenet_keeper] Post-fetching data for update...(301)
[2026-03-31T05:10:21Z INFO  stakenet_keeper] Cranking Steward...
[2026-03-31T05:10:21Z INFO  stakenet_keeper::entries::crank_steward] Update Stake Pool

thread 'main' panicked at keepers/stakenet-keeper/src/entries/crank_steward.rs:119:14:
Could not deserialize vote account: InvalidAccountData
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Solution

- Import `VoteStateV3` from `solana-vote-interface` crate